### ISSUE TITLE
Not find Create post option in your site

### ISSUE THREAD

**Issue by rituraj-m** [AlexP11223/JavaSpringMvcBlog#1]

**Comment by rituraj-m** [comment]
How to create a new post in your site>

**Comment by AlexP11223** [comment]
See the README:

> Username/password auth, **admin can add/edit/delete blog posts**, users (after registration) can add comments, vote (+1/-1) for posts and comments.

> The project is deployed here http://109.120.169.99:8080/blog, admin username/password — admin/pass123, the same password for other users, Alice/Bob/User1-5.

**Comment by rituraj-m** [comment]
I registered with a name after that logged in via that name but after that I can't find create post option. Why the create post option not come this time?

**Comment by AlexP11223** [comment]
Please read the README.

Only admins can create posts and in this simple implementation there is only 1 admin (set in the database). So to create posts you can log in as admin with the username/password specified in README.
